spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    driver-class-name: org.h2.Driver
    username: sa
    password: 1234
  h2:
    console:
      enabled: true
      path: /h2


## Hibernate
  jpa:
    show-sql: true
    properties:
      hibernate:
        formate_sql=true



